### ISSUE TITLE
Logic & Input restructuring

### ISSUE THREAD

**Issue by MaxisMaximov** [MaxisMaximov/manufacture#22]
Rewrite Logic to get rid of Interactions enum and allow for gamestates + events
And Input to get rid of hard-coded keybinds

**Comment by MaxisMaximov** [comment]
Here's the plan:

- [x] #23 part I: Components
  - [x] **Create `gmCompEx` Trait**
    - *pub fn COMP_ID() -> `&'static str`*  
      `&str` to sepparate components once modding comes into place  
      And a function cuz `const` is *compile*time, and I want *run*time
    - *pub type COMP_STORAGE: `gmStorageEx`*
  - [x] **Create some components**
    - [x] gmCompHealth
      - *val: `u16`* -- 65k health is WAY more than enough -- If you somehow go over that, you're dumb
    - [x] gmCompPosition
      - *x: `usize`* -- Eventually will replace with floats. Mayhaps
      - *y: `usize`*
    - [x] gmCompVelocity
      - *x: `usize`*
      - *y: `usize`*
    - [x] gmCompTerrainChunk
      - *cells: `[STYLESET; CHUNK_X * CHUNK_Y]`* -- Styleset is temporary
      - *needsUpdate: `bool`* -- Does it need to get rerendered
    - [x] gmCompRender
      - *size: `VECTOR2`*
      - *sprite: `Vec<STYLESET>`* -- Will later be replaced by a "proper" graphical set
      - *visible: `bool`*
    - [x] gmCompPlayerController -- Defines if the object is the player character
      - *active: `bool`*


- [x] #23 part II: Entities
  - [x] **Create a base `gmObj` struct -- GM is for GaMe, not Gmod**
    Empty, they don't hold any data
  - [x] **Create a `gmObjBuilder` struct**
    - *id: `u16`*
    - *worldCompMapRef: `WORLD_compStorage`>`*
    - [x] *fn new(IN_id: `u16`, IN_worldCompRef: `&mut World`) -> `Self`*
    - [x] *fn<T> addComp(IN_comp: `T`) -> `Self` where `T`: `gmCompEx`*  
      Adds component to the entity through the referenced World Component storage  
      Returns `Self` so you can chain
    - [x] *fn finish() -> `u16`*  
      Just a finishing touch  
      Returns an index for debug -- Or Player ID association
    - [x] *fn<T> fromPrefab(IN_prefab: `&T`) -> `Self` where `T`: `gmObjPrefabEx`*  
      Constructs the entity from a prefab  
      Basically calls `spawn` onto the input struct

- [x] #23 part III: Prefabs
  - [x] **Create a `gmObjPrefEx` trait**
    - *pub fn spawn(`&self`, IN_worldCompMap: `WORLD_CompStorage`)*  
    Prefab trait, requires `Default` trait for ease of use
  - [x] **Create some Prefabs**
    - gmObjPrefPlayer -- Yeah just one lol
      - *gmCompHealth: `100`*
      - *gmCompPosition: `0, 0`*
      - *gmCompVelocity: `0, 0`*
      - *gmCompRender*
        - *size: `1, 1`*
        - *sprite: `[('P', WHITE, CYAN)]`*
        - *visible: `true`*
      - *gmCompCtrlPlayer: `true`*


- [x] #23 part III: Storage
  - [x] **Create a rudimentary `gmStorageEx<T>` trait for components storage**
    - *fn get(IN_id: `u16`) -> `Option<&T`>*
    - *fn get_mut(IN_id: `u16`) -> `Option<&mut T>`*
    - *fn insert(IN_id: `u16`, IN_item: `T`)*
    - *fn insertNextFree(IN_item: `T`) -> `u16`*  
      Inserts at the next free index  
      Generally speaking:  
      - Check `nextFree` BTreeMap for lowest key
      - If found, insert at that index into base and remove from `nextFree`
      - If not found, then get the size/length of base and insert at that index  
        The length of base is always `lastIndex + 1`
    - *fn remove(u16) -> `Option<T>`*  
      Structs with `nextFree` BTreeMaps take the removed index and put it into `nextFree`
    - *fn cleanFarEntries()*  
      Clean the `nextFree` BTreemaps to remove entries that are too far ahead  
      So basically check what the last index in base is currently, anything above it should be removed  
      Call it every 10-20 removes to not waste memory
    - *fn iter() -> `Iter`* -- Return any iterator you want
    - *fn iter_mut() -> `IterMut`* -- Same here

  - [x] **Create custom `storageMap` types**
    - [x] sMBtreeMap<T>
      - *innerMap: `BTreeMap`*
        - *k: `u16`*
        - *v: `T`*
      - *nextFree: `BTreeMap`*
        - *k: `u16`*
        - *v: `bool`*
        - Why a BTreeMap?
        - Cuz then I can get the lowest key easily
        - Bool as Value is completely unnecessary, but compiler cries about Maps without a Value type
    - [ ] sMIndexVec<T>
      - *innerVec: `Vec<idxVecIndex<T>>`*
      - *head: `Option<usize>`*
      - sM_indexVec works similar to IndexMap crate, but it checks if the removed element is last, if it is, remove it **completely**
      - i.e. standard Vec.remove, but doesn't shift all other entries
      - [ ] Create a tiny `idxVecIndex<T>` enum for it
        - *occupied(`T`)*
        - *nextFree(`usize`)*
        - *EOL*
    - [x] sMMapDenseVec<T>
      - *innerProxyMap: BTreeMap*
        - *k: `u16`*
        - *v: `usize`*
      - *nextFree: BTreeMap*
        - *k: `u16`*
        - *v: `bool`*
      - *innerDenseVec: Vec<T>*
      - Basically:
        - First BTreeMap is the unshifting "Proxy"
        - The Vec is the one holding actual data
        - When an index is removed, it takes the *last* Vec element, pops it and shifts to the position of the removed index, also updating it's BTreeMap value
          - Obviously checks if it's the last element
  - [x] **impl `gmStorageEx` for all of them**
    - [x] sMBTreeMap
    - [ ] sMIndexVec
    - [x] sMMapDenseVec


- [x] #23 part VI: Events
  - [x] **Create `gmEventEx` trait**
    - *pub fn EV_ID() -> `&'static str`*
  - [x] **Create some events**
    - gmEvGmObjSpawn
      - *ID: `u16`*
      - *prefID: `&'static str`*
    - gmEvGmObjDespawn
      - *ID: `u16`*
      - *prefID: `&'static str`*
    - gmEvTileChange
      - *pos: `gmCompPosition`*


- [x] #23 part V: Resources
  - [x] **Create `gmResourceEx` trait**
    - *pub fn RES_ID() -> `&str`* -- Just like with `gmCompEx`, to identify it
  - [ ] **Create some Resources**
    - [x] gmResPrefabs
      - *res: `Hashmap`*
        - *k: `&str`*
        - *v: `Box<gmObjPrefEx>`*
    - [x] gmResGmPInput
      - *res: `gmKeyCode`* -- This will later be replaced by *full* keyboard state -- WIll also add other player IDs
    - [x] gmResGmPState
      - *res: `Box<dyn gmPStateEx>`*  
        A simple empty `gmPStateEx` trait to go along with it  
        States:
        - *gmPStateWalk*
        - *gmPStateFly*
    - [x] gmResDeltaT
      - *res: `Duration`*
    - [x] gmResGmState
      - *res: `gmState`*
    - [x] gmResEvents
      - *bufferA: `Vec<Box<dyn gmEventEx>>`*
      - *bufferB: `Vec<Box<dyn gmEventEx>>`*
      - *activeBuffer: `bool`*  
        0 for A, 1 for B
      - [ ] *pub fn<T> sendEvent(IN_event: `T`) where `T`: `gmEventEx`*
      - [x] *pub fn<T> getEvent(IN_event: `T`) -> `Vec<T>` where `T`: `gmEventEx`*
      - [x] *pub fn<T> getEventMut(IN_event: `T`) where `T`: `gmEventEx`*


- [ ] #23 part IV: World
  - [x] **Create `gmWorld` struct**
    - *entities: `sMBTreeMap<gmObj>`*
    - *resources: `Hashmap`*
      - Alias: `WORLD_resStorage`
      - *k: `&str`*
      - *v: `Box<dyn gmResourceEx>`*
    - *components: `Hashmap`*
      - Alias: `WORLD_compStorage`
      - *k: `&str`*
      - *v: `Box<dyn gmStorageEx>`*

  - [x] **Create `gmWorldEx` trait to go along with it**  
    Makes adding new functions easier without having to look at spaghett  
    Resource/Component removals are a confusus, not sure why would you do it at runtime but feels weird without them
    - Un/Register
      - *fn compReg<T>(`&mut self`) where `T`: `gmCompEx`*  
        If the component is already registered it panik
      - *fn compUnreg<T>(`&mut self`) where `T`: `gmCompEx`*
      - *fn resReg<T>(`&mut self`) where `T`: `gmResourceEx`*  
        Inserts it into Resmap using the Component's ID
      - *fn resUnreg<T>(`&mut self`) where `T`: `gmResourceEx`*  
        Takes the ID of the resource  
        Removes it from the ResMap
    - Add/Remove
      - *fn compInsert<T>(`&mut self`, IN_ID: `u16`) where `T`: `gmCompEx`*  
        Takes the Storage type from the component  
        Creates a Storage for the component  
        Inserts it into CompMap using the Component's ID
      - *fn compRemove<T>(`&mut self`, IN_ID: `u16`) where `T`: `gmCompEx`*  
        Takes the ID of the component  
        Removes it from the CompMap
    - Fetches
      - *fn fetchComp<T>(`&self`) -> `&mut dyn gmStorageEx` where `T`: `gmCompEx`*
      - *fn fetchCompMut<T>(`&mut self`) -> `&mut dyn gmStorageEx` where `T`: `gmCompEx`*
      - *fn fetchRes<T>(`&self`) -> &dyn gmStorageEx where `T`: `gmResourceEx`*
      - *fn fetchResMut<T>(`&mut self`) -> `&mut dyn gmStorageEx` where `T`: `gmResourceEx`*
    - Entities
      - *fn entityAdd(`&mut self`) -> `gmObjBuilder`*
      - *fn entityRemove(`&mut self`, `IN_ID`: `u16`) -> `gmObjBuiler`*  
        Removes all traces of the entity, it's slot in the EntityMap and it's Components

  - [x] **impl `WorldEx` for `World`**
    - [x] Un/Register
      - [x] *fn compReg<T>(`&mut self`) where `T`: `gmCompEx`*
      - [x] *fn compUnreg<T>(`&mut self`) where `T`: `gmCompEx`*
      - [x] *fn resReg<T>(`&mut self`) where `T`: `gmResourceEx`*
      - [x] *fn resUnreg<T>(`&mut self`) where `T`: `gmResourceEx`*
    - [ ] Add/Remove
      - [ ] *fn compInsert<T>(`&mut self`) where `T`: `gmCompEx`*
      - [ ] *fn compRemove<T>(`&mut self`) where `T`: `gmCompEx`*
    - [x] Fetches
      - [x] *fn fetchComp<T>(`&self`) -> `&mut dyn gmStorageEx` where `T`: `gmCompEx`*
      - [x] *fn fetchCompMut<T>(`&mut self`) -> `&mut dyn gmStorageEx` where `T`: `gmCompEx`*
      - [x] *fn fetchRes<T>(`&self`) -> &dyn gmStorageEx where `T`: `gmResourceEx`*
      - [x] *fn fetchResMut<T>(`&mut self`) -> `&mut dyn gmStorageEx` where `T`: `gmResourceEx`*
    - [x] Entities
      - [x] *fn entityAdd(`&mut self`) -> `gmObjBuilder`*
      - [x] *fn entityRemove(`&mut self`, `IN_ID`: `u16`)*


- [ ] #23 Part I: States
  - [ ] **Create an enum of gmPState** -- Will maybe replace with a trait
    - *pControl* -- Yes. Just one. For now
  - [ ] **Create an enum of gmState** -- Not the same as playerStates
    - *playerPause* -- Stop players from doing anything, also prevents anything from doing anything to them
    - *worldPause* -- Stops everything in the world
    - *machinePause* -- Stops all machinery from being processed


- [ ] #23 part IV: Systems
  - [x] **Create System trait**
    - *fn SYS_ID() -> `&'static str`*
    - *fn execute(IN_world: `&mut World`) -> `Result<(), ()>`* -- Result is for error stuff  
      And a small documentation to it  
      But basically you call `.fetch` or `.fetchMut` on World to get data  
      Will automate it later
  - [ ] **Create some systems**
    - [x] *Input Read system*
      - Operation:  
        *Get user input from keyboard*
      - ReqData:  
        *fetchResMut::`gmResPInput`*
    - [ ] Player Controller
      - ReqData:  
        *fetchRes::`<gmResPInput>`*  
        *fetch::`<gmCompVelocity>`*  
        *fetchMut::`<gmResEvents>`*
      - Operation:  
        *Process player input*
    - [ ] Movement system
      - ReqData:  
        *fetch::`<gmCompVelocity>`*  
        *fetchMut::`<gmCompPosition>`*
      - Operation:  
        *Add Velocity to Position for objects*
    - [ ] *Entity system*  
      Runs after *all other systems* have finished  
      Why? So that there's no inconsistencies when one system iterates over the entity but not the other
      - ReqData:  
        *fetch::`gmResGmObjDeSpawn`*
      - Operation:  
        *De/Spawn entities*
    - [ ] *Chunk system*
      - Operation:  
        *Update chunks and their sprites*  
        Will later add a proper chunk system
      - Subroutines:
        - *Update Chunks*
          - ReqData:  
            *fetchMut::`gmCompTerrainChunk`*  
            *fetchResMut::`gmResEvents`*
        - *Update Sprites*
          - ReqData:  
            *fetch::`gmCompTerrainChunk`*  
            *fetchMut::`gmCompRender`*
    - [ ] *Render system*  
      Runs *dead last*
      - Operation:  
        *Render everything*
      - Subroutines:
        - *world*
          - Data:  
            *innerBuffer: `RENDER_BUFFER`*
          - ReqData:  
            *fetch::`gmCompTerrainChunk`* -- Iterate over the ID of these actually -- lol  
            *fetch::`gmCompPosition`*  
            *fetch::`gmCompRender`*
          - Subroutines -- Yes subroutines for a subroutine lol
            - *Chunks*  
              *Check distance to all current chunks in relation to player's chunk*  
              *Discard any chunks that are outside the chunk render distance*  
              *Discard any chunks that are outside the render border*
              - By adding `RENDER::WORLDMARGIN` and `RENDER::WORLDRADIUS` together  
              - Anything outside the margin is *definetly* not visible  

              *Render all chunks to own buffer*
            - *Entities*  
              *Check distance to all currently loaded entities*  
              *Discard any entities that are too far*  
              *Take entity sprites and render them to own buffer*
        - *UI* -- hardcoded borders for now


- [ ] #23 part VI: Dispatcher
  - **Create `gmDispatcher` struct**
    - *systems: `Vec<Box<dyn gmSystemEx>>`*
  - **Create `gmDispatcherEx` trait to go along with it**
    - *pub fn dispatch(`&mut self`, IN_world: `&mut gmWorld`)*  
      Iterates over the Systems Vec and fires all of them  
      Will later do a proper dispatcher
    - *pub fn<T> addSystem(`&mut self`, IN_system: `T`) where `T`: `gmSystemEx`*
    - *pub fn<T> removeSystem(`&mut self`) where `T`: `gmSystemEx`*
  
  - **Impl `gmDispatcherEx` for `gmDispatcher`**
    - [ ] *pub fn dispatch(`&mut self`, IN_world: `&mut gmWorld`)*
    - [ ] *pub fn<T> addSystem(`&mut self`, IN_system: `T`) where `T`: `gmSystemEx`*
    - [ ] *pub fn<T> removeSystem(`&mut self`) where `T`: `gmSystemEx`*


- [ ] #23 Part IX: Filing
  - [ ] **Create directories**
    - **manufacture**  
      This is where everything about the base game is stored
    - **engine**  
      This is where all the base stuff is located at  
      A.k.a. Traits, base structs like World etc.
  - [ ] **Create `manufacture` subfolders**
    - components
    - systems
    - resources
    - events
    - sprites
    - prefabs
  - [ ] **Create `manufacture` files**  
    This will serve as the basis for mods
    - `lib.rs`  
      Exports
    - `prelude.rs`  
      Stuff for API -- TODO LATER
    - `init.rs`  
      Registers everything in the game
    - *components*
      - `mod.rs`  
        Houses all the components for now
    - *systems*
      - `mod.rs`
      - `PController.rs`
      - `movement.rs`
      - `render.rs`
    - *resources*
      - `mod.rs`
    - *events*
      - `mod.rs`
    - *sprites* -- TEMPORARILY STORES SPRITES AS .rs FILES -- DO NOT RELY MUCH UNTIL I FIGURE OUT OPENGL OR VULKAN
      - `mod.rs`
      - `player.rs`
    - *prefabs*
      - `mod.rs`
      - `player.rs`
  - [ ] **Create `engine` files**
    - `lib.rs`
    - `prelude.rs`
      - All necessary exports
    - `component.rs`
    - `system.rs`
    - `resource.rs`
    - `event.rs`
    - `prefab.rs`
    - `dispatcher.rs`
    - `world.rs`
  - [ ] **Move over everything Base ECS into `engine`**  
    The traits and base structs like storage, `gmCompEx` etc.
  - [ ] **Move over everything Manufacture ECS into `manufacture`**
    - [ ] components
    - [ ] systems
    - [ ] resources
    - [ ] events
    - [ ] sprites
    - [ ] prefabs

- [ ] #23 Part VII: Injection
  - [ ] **Merge Manufacture ECS into the main code**
  - [ ] **Clean up any bugs that might occur**

**Comment by MaxisMaximov** [comment]
I FINISHED THE PLAN
Took like 2 months and it turned into a goddamn pecking Manifest

Ignore the inconsistent numbering, it was too amusing to get rid of

**Comment by MaxisMaximov** [comment]
My ramblings:
![IMG_20241115_214112_BURST8](https://github.com/user-attachments/assets/4712d605-28ca-42d2-ae1c-333f23fa9e87)
